### ISSUE TITLE
Переименоваться в `fire-square-style`

### ISSUE THREAD

**Issue by PerchunPak** [fire-square/fire-square-style#33]
Почти 0 плагинов использует этот стиль, зато других репозиториев в разы больше. А так же я бы хотел перенести основной проект `autodonate` на этот темплейт.

@cofob

**Comment by cofob** [comment]
Ну делай.

**Comment by PerchunPak** [comment]
Название слишком длинное, мне кажется. `fire-squad-style` будет лучше.
